config/routes.rb
Rails.application.routes.draw do
    mount Ckeditor::Engine => '/ckeditor'
    root 'home#index'
    devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

    get '/welcome/index' => 'welcome#index', as: 'index_welcome'

    get '/my_profile' => 'profile#show', as: 'my_profile'
    get '/my_profile/index' => 'profile#index', as: 'index_profile'
    get '/my_profile/edit' => 'profile#edit', as: 'edit_profile'
    post '/my_profile/edit' => 'profile#update', as: 'update_profile'
    get '/destinations/details' => 'destinations#details',as: 'destinations_details'
    # Destinations

    get '/destinations' => 'destinations#index', as: 'destinations'
    get '/destinations/search' => 'destinations#search'
    get '/destinations/:type/:id' => 'destinations#show', as: 'destination'
    post '/destinations' => 'destinations#create'

    #Bookmarks
    resources :favorite_tips, only: [:create, :destroy]
    
    get '/bookmarks' => 'bookmarks#index', as: 'bookmarks'

    namespace :admin do
        get '/' => 'home#index'
        resources :users
        resources :countries
        resources :cities
        resources :attractions
        resources :categories
        resources :tips, only: [:index, :edit, :update, :destroy, :show]
        resources :tip_flags, only: [:index, :show, :destroy]
    end

    get '/d/:country_name_or_attraction_name' => 'destinations#show', as: 'country_or_attraction'
    get '/d/:country_name_or_attraction_name/tag/*tags' => 'destinations#show'
    get '/d/:country_name/:city_or_attraction_name' => 'destinations#show', as: 'city_or_attraction_name'
    get '/d/:country_name/:city_or_attraction_name/tag/*tags' => 'destinations#show'
    get '/d/:country_name/:city_name/:attraction_name' => 'destinations#show', as: 'attraction_name'
    get '/d/:country_name/:city_name/:attraction_name/tag/*tags' => 'destinations#show'

    get '/u/:username' => 'users#show', as: 'user_profile'

    resources :tips do
        resources :comments
        
        collection do
            get 'destination_search_autocomplete'
        end
        
        member do
            get 'body'
            post 'flag'
            post 'vote'
        end
    end
    post '/comments/vote_comment_reply' => 'comments#vote_comment_reply', as: 'add_vote_comment_reply'
    post '/comments/vote_comment' => 'comments#vote_comment', as: 'add_vote_comment'
    post '/comments/create_comment_reply' => 'comments#create_comment_reply', as: 'create_comment_reply'
    post '/tips/flag_tip' => 'tips#create_flag_tip', as: 'add_flag_tip'
    post '/tips/vote_tip' => 'tips#vote_tip', as: 'add_vote_tip'
    post '/tips/favorite_tip' => 'tips#favorite_tip', as: 'add_favorite_tip'
    get '/tips/detail' => 'tips#detail', as: 'details_tips'

    get '/d/:country_name/:city_or_attraction_name/new_tip' => 'destinations#new_tip'
    get '/d/:country_name/:city_name/:attraction_name/new_tip' => 'destinations#new_tip'

    get '/about' => 'home#about'
    get '/terms' => 'home#terms'
    get '/privacy' => 'home#privacy'
    get '/careers' => 'home#careers'


    get '/api/countries' => 'home#countries', as: 'api_get_countries'
    get '/api/cities' => 'home#cities', as: 'api_get_cities'

    
    
end

app/controllers/admin/attractions_controller.rb
class Admin::AttractionsController < AdminController

    layout 'admin'
    before_action :authenticate_user!

    def index
        @attractions = Attraction.get_active.order('id ASC')
    end

    def new
        @attraction = Attraction.new
    end

    def create
        @attraction = Attraction.new attraction_params
        
        if @attraction.save
            redirect_to admin_attraction_path(@attraction)
        else            
            render 'new'
        end
    end

    def edit  
        @attraction = Attraction.find params[:id]     
    end

    def show
        @attraction = Attraction.find params[:id]
    end

    def update
        @attraction = Attraction.find params[:id]
        if @attraction.update(attraction_params)           
            redirect_to admin_attraction_path(@attraction)
        else            
            render 'edit'
        end
    end

    def destroy
        @attraction = Attraction.find params[:id]
        # @attraction.inactivate # TODO: Defined inactivate actions
        redirect_to admin_attractions_path
    end
  
    private
    def attraction_params
        params.require(:attraction).permit!
    end
end

app/views/admin/attractions/_form.html.erb
<%= form_for([:admin,@attraction]) do |f| %>

<table class="table">

    <tr>
        <td width="30%"><%= f.label :name, "Name" %></td>
        <td><%= f.text_field :name ,class: 'form-control' %></td>
    </tr>

    <tr>
        <td width="30%"><%= f.label :slug, "Slug" %></td>
        <td><%= f.text_field :slug ,class: 'form-control' %></td>
    </tr>
    
    <tr>
        <td><%= f.label :city_id,"City" %></td>
        <td><%= f.collection_select :city_id, City.all, :id, :name,  {prompt: "Select city or leave it blank"}, {class: "form-control" }%></td> 
    </tr>

    <tr>
        <td><%= f.label :country_id, "Country" %></td>
        <td><%= f.collection_select :country_id, Country.all, :id, :name,  {prompt: "Select country or leave it blank"}, {class: "form-control" }%></td> 
    </tr>

    <tr>
        <td><%= f.label :status, "Status" %></td>
        <td><%= f.select :status, options_for_select(Attraction.get_status_for_select, @attraction.status), {:include_blank => "Select status"},{:class => "form-control"} %></td>
    </tr>
    
</table>

<div class="row">
    <div class="col-md-12 text-right">
        <%= link_to "Back to the list of cities", admin_attractions_path, class: 'btn btn-default' %>
        <%= link_to "Cancel", admin_attraction_path(@attraction), class: 'btn btn-warning' if !@attraction.id.nil? %>
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

<% end -%>

app/views/admin/attractions/edit.html.erb
<h1>Edit attraction</h1>
<%= notice.html_safe if notice %>
<ul>
    <% @attraction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end -%>
</ul>
<%= render 'form' %>
<div style="clear: both;"></div>

app/views/admin/attractions/index.html.erb
<div class="row">
    <div class="col-md-12">
        <h1>
            List of attractions
            <%= link_to "Create attraction", new_admin_attraction_path, class: 'btn btn-primary' %>
        </h1>
        <%= notice.html_safe if notice %>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>  
                    <th>Slug</th>
                    <th>Location</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <% @attractions.each do |attraction| %>
                <tr>
                    <td><%= attraction.id %></td>
                    <td><%= attraction.name %></td>
                    <td><%= attraction.slug %></td>
                    <td><%= attraction.location_name %></td>
                    <td><%= attraction.status_name %></td>
                    <td><%= link_to "Details", admin_attraction_path(attraction), class: 'btn btn-primary btn-xs' %></td>
                </tr>
                <% end -%>
            </tbody>
        </table>
    </div>
</div>

app/views/admin/attractions/new.html.erb
<h1>Create attraction</h1>
<%= notice.html_safe if notice %>
<ul>
    <% @attraction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end -%>
</ul>
<%= render 'form' %>
<div style="clear: both;"></div>

app/views/admin/attractions/show.html.erb
<div class="row">
    <div class="col-md-12">
        <h1>
             Details
            <%= link_to 'Back', admin_attractions_path, class: 'btn btn-default' %>
            <%= link_to "Edit", edit_admin_attraction_path(@attraction), class: 'btn btn-primary' %>            
            <%= link_to "Delete", admin_attraction_path(@attraction), class: 'btn btn-danger', data: {method: 'DELETE', confirm: 'are you sure?'} %>
        </h1>
        <%= notice.html_safe if notice %>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <td><b>Id</b></td>
                <td><%= @attraction.id %></td>
            </tr>
            <tr>
                <td><b>Name:</b></td>
                <td><%= @attraction.name %></td>
            </tr>
            <tr>
                <td><b>Slug:</b></td>
                <td><%= @attraction.slug %></td>
            </tr>
            <tr>
                <td><b>City:</b></td>
                <td><%= @attraction.city.name rescue "Not set" %></td>
            </tr>
            <tr>
                <td><b>Country:</b></td>
                <td><%= @attraction.country.name rescue "Not set" %></td>
            </tr>
            <tr>
                <td><b>Status:</b></td>
                <td><%= @attraction.status_name %></td>
            </tr>
        </table>
    </div>
</div>