config/routes.rb
Rails.application.routes.draw do
    mount Ckeditor::Engine => '/ckeditor'
    root 'home#index'
    devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

    get '/welcome/index' => 'welcome#index', as: 'index_welcome'

    get '/my_profile' => 'profile#show', as: 'my_profile'
    get '/my_profile/index' => 'profile#index', as: 'index_profile'
    get '/my_profile/edit' => 'profile#edit', as: 'edit_profile'
    post '/my_profile/edit' => 'profile#update', as: 'update_profile'
    get '/destinations/details' => 'destinations#details',as: 'destinations_details'
    # Destinations

    get '/destinations' => 'destinations#index', as: 'destinations'
    get '/destinations/search' => 'destinations#search'
    get '/destinations/:type/:id' => 'destinations#show', as: 'destination'
    post '/destinations' => 'destinations#create'

    #Bookmarks
    resources :favorite_tips, only: [:create, :destroy]
    
    get '/bookmarks' => 'bookmarks#index', as: 'bookmarks'

    namespace :admin do
        get '/' => 'home#index'
        resources :users
        resources :countries
        resources :cities
        resources :attractions
        resources :categories
        resources :tips, only: [:index, :edit, :update, :destroy, :show]
        resources :tip_flags, only: [:index, :show, :destroy]
    end

    get '/d/:country_name_or_attraction_name' => 'destinations#show', as: 'country_or_attraction'
    get '/d/:country_name_or_attraction_name/tag/*tags' => 'destinations#show'
    get '/d/:country_name/:city_or_attraction_name' => 'destinations#show', as: 'city_or_attraction_name'
    get '/d/:country_name/:city_or_attraction_name/tag/*tags' => 'destinations#show'
    get '/d/:country_name/:city_name/:attraction_name' => 'destinations#show', as: 'attraction_name'
    get '/d/:country_name/:city_name/:attraction_name/tag/*tags' => 'destinations#show'

    get '/u/:username' => 'users#show', as: 'user_profile'

    resources :tips do
        resources :comments
        
        collection do
            get 'destination_search_autocomplete'
        end
        
        member do
            get 'body'
            post 'flag'
            post 'vote'
        end
    end
    post '/comments/vote_comment_reply' => 'comments#vote_comment_reply', as: 'add_vote_comment_reply'
    post '/comments/vote_comment' => 'comments#vote_comment', as: 'add_vote_comment'
    post '/comments/create_comment_reply' => 'comments#create_comment_reply', as: 'create_comment_reply'
    post '/tips/flag_tip' => 'tips#create_flag_tip', as: 'add_flag_tip'
    post '/tips/vote_tip' => 'tips#vote_tip', as: 'add_vote_tip'
    post '/tips/favorite_tip' => 'tips#favorite_tip', as: 'add_favorite_tip'
    get '/tips/detail' => 'tips#detail', as: 'details_tips'

    get '/d/:country_name/:city_or_attraction_name/new_tip' => 'destinations#new_tip'
    get '/d/:country_name/:city_name/:attraction_name/new_tip' => 'destinations#new_tip'

    get '/about' => 'home#about'
    get '/terms' => 'home#terms'
    get '/privacy' => 'home#privacy'
    get '/careers' => 'home#careers'


    get '/api/countries' => 'home#countries', as: 'api_get_countries'
    get '/api/cities' => 'home#cities', as: 'api_get_cities'

    
    
end

app/models/country.rb
class Country < ApplicationRecord

	include Statusable
    include Destinatable

    default_scope { where(status: Status[:active]) }

	has_many :cities 
    has_many :tips, -> {where(status: Tip::Status[:active])}

	validates :name, presence: true

    def full_name
        name
    end

    def entity_type
        'country'
    end
end

app/controllers/admin/countries_controller.rb
class Admin::CountriesController < AdminController

    layout 'admin'
    before_action :authenticate_user!

    def index
        @countries = Country.get_active.order('id ASC')
    end

    def new
        @country = Country.new
    end

    def create
        @country = Country.new country_params
        
        if @country.save
            redirect_to admin_country_path(@country)
        else            
            render 'new'
        end
    end

    def edit  
        @country = Country.find params[:id]     
    end

    def show
        @country = Country.find params[:id]
    end

    def update
        @country = Country.find params[:id]
        if @country.update(country_params)           
            redirect_to admin_country_path(@country)
        else            
            render 'edit'
        end
    end

    def destroy
        @country = Country.find params[:id]
        # @country.inactivate # TODO: Defined inactivate actions
        redirect_to admin_countries_path
    end
  
    private
    def country_params
        params.require(:country).permit!
    end
end

app/views/admin/countries/_form.html.erb
<%= form_for([:admin,@country]) do |f| %>

<table class="table">

    <tr>
        <td width="30%"><%= f.label :name, "Name" %></td>
        <td><%= f.text_field :name ,class: 'form-control' %></td>
    </tr>
    <tr>
        <td width="30%"><%= f.label :slug, "Slug" %></td>
        <td><%= f.text_field :slug ,class: 'form-control' %></td>
    </tr>
    <tr>
        <td><%= f.label :status, "Status" %></td>
        <td><%= f.select :status, options_for_select(Country.get_status_for_select, @country.status), {:include_blank => "Select status"},{:class => "form-control", :required => true} %></td>
    </tr>
    
</table>

<div class="row">
    <div class="col-md-12 text-right">
        <%= link_to "Back to the list of countries", admin_countries_path, class: 'btn btn-default' %>
        <%= link_to "Cancel", admin_country_path(@country), class: 'btn btn-warning' if !@country.id.nil? %>
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

<% end -%>

app/views/admin/countries/edit.html.erb
<h1>Edit country</h1>
<%= notice.html_safe if notice %>
<ul>
    <% @country.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end -%>
</ul>
<%= render 'form' %>
<div style="clear: both;"></div>

app/views/admin/countries/index.html.erb
<div class="row">
    <div class="col-md-12">
        <h1>
            List of countries
            <%= link_to "Create country", new_admin_country_path, class: 'btn btn-primary' %>
        </h1>
        <%= notice.html_safe if notice %>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Slug</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <% @countries.each do |country| %>
                <tr>
                    <td><%= country.id %></td>
                    <td><%= country.name %></td> 
                    <td><%= country.slug %></td>
                    <td><%= country.status_name %></td>
                    <td><%= link_to "Details", admin_country_path(country), class: 'btn btn-primary btn-xs' %></td>
                </tr>
                <% end -%>
            </tbody>
        </table>
    </div>
</div>

app/views/admin/countries/new.html.erb
<h1>Create country</h1>
<%= notice.html_safe if notice %>
<ul>
    <% @country.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end -%>
</ul>
<%= render 'form' %>
<div style="clear: both;"></div>

app/views/admin/countries/show.html.erb
<div class="row">
    <div class="col-md-12">
        <h1>
             Details
            <%= link_to 'Back', admin_countries_path, class: 'btn btn-default' %>
            <%= link_to "Edit", edit_admin_country_path(@country), class: 'btn btn-primary' %>            
            <%= link_to "Delete", admin_country_path(@country), class: 'btn btn-danger', data: {method: 'DELETE', confirm: 'are you sure?'} %>
        </h1>
        <%= notice.html_safe if notice %>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <td><b>id</b></td>
                <td><%= @country.id %></td>
            </tr>
            <tr>
                <td><b>Name:</b></td>
                <td><%= @country.name %></td>
            </tr>  
            <tr>
                <td><b>Slug:</b></td>
                <td><%= @country.slug %></td>
            </tr>
            <tr>
                <td><b>Status:</b></td>
                <td><%= @country.status_name %></td>
            </tr>
        </table>
    </div>
</div>