config/routes.rb
Rails.application.routes.draw do
    mount Ckeditor::Engine => '/ckeditor'
    root 'home#index'
    devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

    get '/welcome/index' => 'welcome#index', as: 'index_welcome'

    get '/my_profile' => 'profile#show', as: 'my_profile'
    get '/my_profile/index' => 'profile#index', as: 'index_profile'
    get '/my_profile/edit' => 'profile#edit', as: 'edit_profile'
    post '/my_profile/edit' => 'profile#update', as: 'update_profile'
    get '/destinations/details' => 'destinations#details',as: 'destinations_details'
    # Destinations

    get '/destinations' => 'destinations#index', as: 'destinations'
    get '/destinations/search' => 'destinations#search'
    get '/destinations/:type/:id' => 'destinations#show', as: 'destination'
    post '/destinations' => 'destinations#create'

    #Bookmarks
    resources :favorite_tips, only: [:create, :destroy]
    
    get '/bookmarks' => 'bookmarks#index', as: 'bookmarks'

    namespace :admin do
        get '/' => 'home#index'
        resources :users
        resources :countries
        resources :cities
        resources :attractions
        resources :categories
        resources :tips, only: [:index, :edit, :update, :destroy, :show]
        resources :tip_flags, only: [:index, :show, :destroy]
    end

    get '/d/:country_name_or_attraction_name' => 'destinations#show', as: 'country_or_attraction'
    get '/d/:country_name_or_attraction_name/tag/*tags' => 'destinations#show'
    get '/d/:country_name/:city_or_attraction_name' => 'destinations#show', as: 'city_or_attraction_name'
    get '/d/:country_name/:city_or_attraction_name/tag/*tags' => 'destinations#show'
    get '/d/:country_name/:city_name/:attraction_name' => 'destinations#show', as: 'attraction_name'
    get '/d/:country_name/:city_name/:attraction_name/tag/*tags' => 'destinations#show'

    get '/u/:username' => 'users#show', as: 'user_profile'

    resources :tips do
        resources :comments
        
        collection do
            get 'destination_search_autocomplete'
        end
        
        member do
            get 'body'
            post 'flag'
            post 'vote'
        end
    end
    post '/comments/vote_comment_reply' => 'comments#vote_comment_reply', as: 'add_vote_comment_reply'
    post '/comments/vote_comment' => 'comments#vote_comment', as: 'add_vote_comment'
    post '/comments/create_comment_reply' => 'comments#create_comment_reply', as: 'create_comment_reply'
    post '/tips/flag_tip' => 'tips#create_flag_tip', as: 'add_flag_tip'
    post '/tips/vote_tip' => 'tips#vote_tip', as: 'add_vote_tip'
    post '/tips/favorite_tip' => 'tips#favorite_tip', as: 'add_favorite_tip'
    get '/tips/detail' => 'tips#detail', as: 'details_tips'

    get '/d/:country_name/:city_or_attraction_name/new_tip' => 'destinations#new_tip'
    get '/d/:country_name/:city_name/:attraction_name/new_tip' => 'destinations#new_tip'

    get '/about' => 'home#about'
    get '/terms' => 'home#terms'
    get '/privacy' => 'home#privacy'
    get '/careers' => 'home#careers'


    get '/api/countries' => 'home#countries', as: 'api_get_countries'
    get '/api/cities' => 'home#cities', as: 'api_get_cities'

    
    
end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
		:recoverable, :rememberable, :trackable, :validatable,
		:omniauthable, omniauth_providers: [:facebook]

	has_many :tips
	has_many :favorites
	has_many :comments

	has_many :user_countries, class_name: 'UserCountry'
	has_many :countries, through: :user_countries

	validates :username, presence: true, uniqueness: true
	
	include Statusable
	include Genderable

	Roles = {normal: 0, admin: 1}

	has_attached_file :avatar, 
		styles: { medium: "300x300>", thumb: "100x100>" }, 
		default_url: "/assets/profile.jpg"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	def is_admin?
		self.role == Roles[:admin]
	end

	def role_name
		return "Administrador" if self.role == Roles[:admin]
		return "Normal" if self.role == Roles[:normal]		
		return "NA"
	end

	def self.roles_for_select
		{
			"Administrador" => Roles[:admin],
			"Normal" => Roles[:normal]			
		}
	end

	def username_capitalized
		self.username.capitalize rescue ""
	end

	def countries_visited_count
		rand(1..70)
	end

	def self.from_omniauth(auth)
 		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
		    user.email = auth.info.email
		    user.password = Devise.friendly_token[0,20]
		    user.username = auth.info.name   
		    # user.image = auth.info.image 
		    
		end
	end

	def count_destinations
		Tip.select('attraction_id,city_id,country_id').where(user_id: self.id, status: Tip::Status[:active]).group('attraction_id,city_id,country_id').length
	end

	def count_tip_countries
		Tip.select('country_id').where(user_id: self.id, status: Tip::Status[:active]).group('country_id').length
	end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

    layout 'admin'
    before_action :authenticate_user!

    def index
        @users = User.get_active.order('id ASC')
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new user_params
        @user.password, @user.password_confirmation = @user.email
        if @user.save
            redirect_to admin_user_path(@user)
        else            
            render 'new'
        end
    end

    def edit
        @user = User.find params[:id]
    end

    def show
        @user = User.find params[:id]
    end

    def update
        @user = User.find(current_user.id)
        if @user.update(user_params)           
            redirect_to admin_user_path(@user)
        else            
            render 'edit'
        end
    end

    def destroy
        @user = User.find(current_user.id)
        # @user.inactivate # TODO: Defined inactivate actions
        redirect_to admin_users_path
    end
  
    private
    def user_params
        params.require(:user).permit!
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :authenticate_user!, except: [:show]
    layout 'application'

    def show
        username = params[:username].downcase ||= ""
        @user = User.where('lower(username) = ?', username).first
        @tips = Tip.where(user_id: @user.id)
        redirect_to root_path, notice: "User not found" and return if @user.nil?
    end

    def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	    #user.name = auth.info.name   # assuming the user model has a name
	    #user.image = auth.info.image # assuming the user model has an image
	    # If you are using confirmable and the provider(s) you use validate emails, 
	    # uncomment the line below to skip the confirmation emails.
	    # user.skip_confirmation!
	  end
	end

end

app/views/admin/users/_form.html.erb
<%= form_for([:admin,@user]) do |f| %>

<table class="table">

    <tr>
        <td width="30%"><%= f.label :username, "Username" %></td>
        <td><%= f.text_field :username ,class: 'form-control' %></td>
    </tr>    
    <tr>
        <td><%= f.label :email, "Email" %></td>
        <td><%= f.text_field :email, class: 'form-control' %></td>
    </tr>
    <tr>
        <td><%= f.label :role, "Role" %></td>
        <td><%= f.select :role, options_for_select(User.roles_for_select, @user.role), {include_blank: 'select a role from the list'}, {class: 'form-control'} %></td>
    </tr>
    
</table>

<div class="row">
    <div class="col-md-12 text-right">
        <%= link_to "Back to the list of users", admin_users_path, class: 'btn btn-default' %>
        <%= link_to "Cancel", admin_user_path(@user), class: 'btn btn-warning' if !@user.id.nil? %>
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

<% end -%>

app/views/admin/users/edit.html.erb
<h1>Edit user</h1>
<%= notice.html_safe if notice %>
<ul>
    <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end -%>
</ul>
<%= render 'form' %>
<div style="clear: both;"></div>

<h2>Edit password</h2>
<%= form_for([:admin,@user]) do |f| %>
<table class="table">
    <tr>
        <td width="30%"><%= f.label :password, "Password" %></td>
        <td><%= f.password_field :password, class: 'form-control' %></td>
    </tr>
    <tr>
        <td><%= f.label :password_confirmation, "Password confirmation" %></td>
        <td><%= f.password_field :password_confirmation, class: 'form-control' %></td>
    </tr>
</table>
<button type="submit" class="btn btn-primary pull-right">Submit</button>
<% end -%>
<div style="clear: both;"></div>

app/views/admin/users/index.html.erb
<div class="row">
    <div class="col-md-12">
        <h1>
            List of user
            <%= link_to "Create user", new_admin_user_path, class: 'btn btn-primary' %>
        </h1>
        <%= notice.html_safe if notice %>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Username</th>                    
                    <th>Email</th>
                    <th>Role</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <% @users.each do |user| %>
                <tr>
                    <td><%= user.id %></td>
                    <td><%= user.username %></td>                    
                    <td><%= user.email %></td>
                    <td><%= user.role_name %></td>
                    <td><%= render_badge(user.badge_color,user.status_name) %></td>
                    <td><%= link_to "Details", admin_user_path(user), class: 'btn btn-primary btn-xs' %></td>
                </tr>
                <% end -%>
            </tbody>
        </table>
    </div>
</div>

app/views/admin/users/new.html.erb
<h1>Create user</h1>
<%= notice.html_safe if notice %>
<ul>
    <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end -%>
</ul>
<%= render 'form' %>
<div style="clear: both;"></div>

app/views/admin/users/show.html.erb
<div class="row">
    <div class="col-md-12">
        <h1>
            User Details
            <%= link_to 'Back to the list of users', admin_users_path, class: 'btn btn-default' %>
            <%= link_to "Edit", edit_admin_user_path(@user), class: 'btn btn-primary' %>            
            <%= link_to "Delete", admin_user_path(@user), class: 'btn btn-danger', data: {method: 'DELETE', confirm: 'are you sure?'} %>
        </h1>
        <%= notice.html_safe if notice %>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <td><b>Username:</b></td>
                <td><%= @user.username %></td>
            </tr>            
            <tr>
                <td><b>Email:</b></td>
                <td><%= @user.email %></td>
            </tr>
            <tr>
                <td><b>Creation date:</b></td>
                <td><%= @user.created_at %></td>
            </tr>
            <tr>
                <td><b>Role:</b></td>
                <td><%= @user.role_name %></td>
            </tr>            
            <tr>
                <td><b>Status:</b></td>
                <td><%= @user.status_name %></td>
            </tr>
            <tr>
                <td><b>Date of last entry:</b></td>
                <td><%= @user.last_sign_in_at %></td>
            </tr>
        </table>
    </div>
</div>